/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CurrentTime {
    }
    interface ItemList {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyItem {
        "description": string;
        "indx": number;
    }
    interface MyToggleButton {
    }
}
declare global {
    interface HTMLCurrentTimeElement extends Components.CurrentTime, HTMLStencilElement {
    }
    var HTMLCurrentTimeElement: {
        prototype: HTMLCurrentTimeElement;
        new (): HTMLCurrentTimeElement;
    };
    interface HTMLItemListElement extends Components.ItemList, HTMLStencilElement {
    }
    var HTMLItemListElement: {
        prototype: HTMLItemListElement;
        new (): HTMLItemListElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyItemElement extends Components.MyItem, HTMLStencilElement {
    }
    var HTMLMyItemElement: {
        prototype: HTMLMyItemElement;
        new (): HTMLMyItemElement;
    };
    interface HTMLMyToggleButtonElement extends Components.MyToggleButton, HTMLStencilElement {
    }
    var HTMLMyToggleButtonElement: {
        prototype: HTMLMyToggleButtonElement;
        new (): HTMLMyToggleButtonElement;
    };
    interface HTMLElementTagNameMap {
        "current-time": HTMLCurrentTimeElement;
        "item-list": HTMLItemListElement;
        "my-component": HTMLMyComponentElement;
        "my-item": HTMLMyItemElement;
        "my-toggle-button": HTMLMyToggleButtonElement;
    }
}
declare namespace LocalJSX {
    interface CurrentTime {
    }
    interface ItemList {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyItem {
        "description"?: string;
        "indx"?: number;
    }
    interface MyToggleButton {
    }
    interface IntrinsicElements {
        "current-time": CurrentTime;
        "item-list": ItemList;
        "my-component": MyComponent;
        "my-item": MyItem;
        "my-toggle-button": MyToggleButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "current-time": LocalJSX.CurrentTime & JSXBase.HTMLAttributes<HTMLCurrentTimeElement>;
            "item-list": LocalJSX.ItemList & JSXBase.HTMLAttributes<HTMLItemListElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-item": LocalJSX.MyItem & JSXBase.HTMLAttributes<HTMLMyItemElement>;
            "my-toggle-button": LocalJSX.MyToggleButton & JSXBase.HTMLAttributes<HTMLMyToggleButtonElement>;
        }
    }
}
